
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ../test.ipynb

import operator

def test(a,b,comp):
    assert comp(a,b), f'{a} does not {comp.__name__} {b}'

def test_eq(a,b):
    test(a,b,operator.eq)

def test_near(a,b,eps=1e-4):
    assert abs(a - b) < eps, f'{a} not within {eps} of {b}'